version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: umbrelsolostrike-ckpool-solo_web_1
      APP_PORT: 4040
  ckpool:
    image: ghcr.io/gbechtel-beck/ckpool-solo-ckpool:latest
    entrypoint: ["/bin/bash", "-c", "rm -rf /ckpool/logs/ckpool.sock && /entrypoint.sh"]
    container_name: umbrelsolostrike-ckpool-solo_ckpool_1
    restart: on-failure
    environment:
      BITCOIN_RPC_URL: "http://$APP_BITCOIN_NODE_IP"
      BITCOIN_RPC_PORT: "$APP_BITCOIN_RPC_PORT"
      BITCOIN_RPC_USER: "$APP_BITCOIN_RPC_USER"
      BITCOIN_RPC_PASS: "$APP_BITCOIN_RPC_PASS"
      STRATUM_PORT: "3333"
      POOL_SIG: "/SoloStrike.io/"
      POOL_FEE: "0"
      MIN_DIFF: "1000"
      START_DIFF: "1000"
      MAX_DIFF: "0"
    volumes:
      - "${APP_DATA_DIR}/logs:/ckpool/logs"
    ports:
      - "3333:3333/tcp"
  web:
    image: ghcr.io/gbechtel-beck/ckpool-solo-ui:latest
    container_name: umbrelsolostrike-ckpool-solo_web_1
    restart: on-failure
    environment:
      CKPOOL_LOG_DIR: "/ckpool/logs"
      PORT: "4040"
      BITCOIN_RPC_URL: "http://$APP_BITCOIN_NODE_IP"
      BITCOIN_RPC_PORT: "$APP_BITCOIN_RPC_PORT"
      BITCOIN_RPC_USER: "$APP_BITCOIN_RPC_USER"
      BITCOIN_RPC_PASS: "$APP_BITCOIN_RPC_PASS"
    volumes:
      - "${APP_DATA_DIR}/logs:/ckpool/logs:ro"
    depends_on:
      - ckpool
